# Generated by Django 4.0.2 on 2022-02-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertype',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
