# Generated by Django 4.0.2 on 2022-02-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype')),
            ],
        ),
    ]
