# Generated by Django 4.0.2 on 2022-02-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0002_supertype_type'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supers',
            name='alter_ego',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supers',
            name='catchphrase',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supers',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supers',
            name='primary_ability',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supers',
            name='secondary_ability',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supers',
            name='super_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype'),
        ),
    ]
