# Generated by Django 4.0.2 on 2022-02-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0002_supertype_type'),
        ('supers', '0003_alter_supers_super_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='super_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_types.supertype'),
        ),
    ]
