# Generated by Django 4.0.2 on 2022-02-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supers', '0004_alter_supers_super_type'),
        ('super_types', '0002_supertype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_date', models.DateTimeField()),
                ('super_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supers.supers')),
                ('super_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_types.supertype')),
            ],
        ),
    ]
